### ISSUE TITLE
Steemdunk: Bugs To Fix

### ISSUE THREAD

**Issue by yemmighto** [samrg472/steemdunk#1]
Hearing about steemdunk as an open source project

##  what is steemdunk
>Steem Dunk is a new automated curation service designed to be easy to use and reliable for the community.
> Being built from the ground up for ease-of-use and reliability, it is now open source as of now with the support of Utopian to keep the servers running. This means the cloud hosted version will now be free to use for everyone! ...Or you can self host the service for yourself if you'd like.

checking the site out at steemdunk.xyz to see how it goes, but there are some things not working on the site. they are blank even after waiting for hours seeing if something will eventually come up but i was surprised nothing showed up.

### Stat space keep rolling

the space schedule as a stat space keep loading and rolling for hours without showing anything at all, up till now it keep rolling
![dunk.PNG](https://steemitimages.com/DQmXnv8tnPcvZeP9KjiZBgcxeAYWP69A1UiwUPhUMikToZ4/dunk.PNG)

### Vote log (previous 7 days)
The vote log (previous 7 days) is empty, at first i thought this space is schedule to show who we vote for in the past 7 days but maybe i thought wrong
![dunk 2.PNG](https://steemitimages.com/DQmZ9q6bTLVs38RCqNc6DXAYFvgqrPBioyY9beDV9gqYNrR/dunk%202.PNG)

If am right, i hope something need to be done maybe they should be fixed, and the site owner can make more enlightening post about steemdunk, so we all can understand more.

check the bug video below
https://youtu.be/gy1c2RtNkJM 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@valchiz/steemdunk-bugs-to-fix">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by samrg472** [comment]
Thanks for the report, the issue has been fixed!
